
- name: Esperar a que SonarQube esté disponible
  uri:
    url: "{{ sonar_host }}/api/system/status"
    method: GET
    return_content: yes
  register: sonar_status
  retries: 20
  delay: 5
  until: sonar_status.status == 200 and '"status":"UP"' in sonar_status.content

- name: Cambiar contraseña del usuario admin (predeterminada)
  uri:
    url: "{{ sonar_host }}/api/users/change_password"
    method: POST
    user: admin
    password: "admin" 
    force_basic_auth: yes
    body_format: form-urlencoded
    body:
      login: admin
      previousPassword: "admin"  # Contraseña predeterminada
      password: "{{ new_password }}"
    status_code: [200, 204]
    validate_certs: no
  register: password_change_result