services:
  jenkins:
    image: jenkins/jenkins:lts-jdk17  # Imagen oficial LTS con Java 17
    container_name: jenkins
    restart: unless-stopped
    ports:
      - "8080:8080"
      - "50000:50000"  # Puerto para agentes JNLP
    volumes:
      - jenkins_data:/var/jenkins_home  # Volumen para persistencia
      - /var/run/docker.sock:/var/run/docker.sock  # Solo si necesitas ejecutar Docker desde Jenkins
      - ./init.groovy.d:/usr/share/jenkins/ref/init.groovy.d  # Mapea tus scripts Groovy
    environment:
      - JENKINS_ADMIN_ID=admin
      - JENKINS_ADMIN_PASSWORD=admin  
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false  # Opcional: Desactiva setup wizard inicial

volumes:
  jenkins_data: