- name: Check jenkins status
  command: echo "Check jenkins status"
  notify: verify jenkins
  
- name: Copiar archivo plugins.txt al contenedor
  copy:
    src: ../files/plugins.txt  
    dest: /home/{{ ansible_user }}/plugins.txt


- name: Copiar archivo plugins.txt al contenedor Jenkins
  command: docker cp /home/{{ ansible_user }}/plugins.txt jenkins:/plugins.txt


- name: Instalar plugins jenkins
  command: docker exec -it jenkins jenkins-plugin-cli --plugin-file /plugins.txt

- name: restart jenkins
  become: true
  command: sudo docker restart jenkins

- name: verify jenkins
  become: true
  uri:
    url: "http://{{ devops_vm_ip }}:8080/login"
    method: GET
    status_code: 200
    timeout: 10
  register: jenkins_status
  retries: 5
  delay: 3
  until: jenkins_status.status == 200  